dist: trusty
sudo: required
language: python
python:
-   "3.11"
install:
-   sudo add-apt-repository -y ppa:fkrull/deadsnakes
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.11 python3.11-dev
-   pip install -r requirements-test.txt
script:
-   ./pep8.sh
-   tox
