# Generated by Django 4.0 on 2021-12-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=500)),
                ('table_name', models.CharField(max_length=500)),
                ('table_owner', models.CharField(max_length=500)),
                ('size_in_bytes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'table',
                'ordering': ('-size_in_bytes',),
                'managed': False,
            },
        ),
    ]
