# Generated by Django 4.0 on 2021-12-28 12:46

from django.conf import settings
from django.db import connection, migrations


def create_view(apps, schema_editor):

    with connection.cursor() as cursor:
        with open(f"{settings.APPS_DIR}/database_size/sql/table.{connection.vendor}.sql") as file:
            cursor.execute(file.read())


class Migration(migrations.Migration):

    dependencies = [
        ('database_size', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_view),
    ]
